annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/kube-version: '>= v1.16.0-0 < v1.29.0-0'
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/rancher-version: '>= 2.7.5-0'
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
apiVersion: v2
appVersion: 1.2.1
description: Kubewarden extension for Rancher Manager
name: kubewarden
type: application
version: 1.2.1
icon: >-
  https://raw.githubusercontent.com/kubewarden/ui/main/pkg/kubewarden/assets/icon-kubewarden.svg
